export const ERROR_CODES = {
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INVALID_JSON: 'INVALID_JSON',
  INVALID_FILE: 'INVALID_FILE',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
};

const DUPLICATE_FIELD_MESSAGES = {
  email: 'Email already registered',
  username: 'Username already taken',
  slug: 'Workspace slug already exists',
};

export const getDuplicateFieldMessage = (field) =>
  DUPLICATE_FIELD_MESSAGES[field] ?? `${field} already exists`;
