import { WORKSPACE_MEMBER_ROLE } from './workspaceMemberRole.js';

export const WORKSPACE_PERMISSION = {
  // Workspace
  VIEW_WORKSPACE: 'VIEW_WORKSPACE',
  UPDATE_WORKSPACE: 'UPDATE_WORKSPACE',
  DELETE_WORKSPACE: 'DELETE_WORKSPACE',
  ARCHIVE_WORKSPACE: 'ARCHIVE_WORKSPACE',

  // Members
  VIEW_MEMBERS: 'VIEW_MEMBERS',
  INVITE_MEMBERS: 'INVITE_MEMBERS',
  REMOVE_MEMBERS: 'REMOVE_MEMBERS',
  CHANGE_MEMBER_ROLE: 'CHANGE_MEMBER_ROLE',

  // Projects
  CREATE_PROJECT: 'CREATE_PROJECT',
  VIEW_PROJECT: 'VIEW_PROJECT',
  UPDATE_PROJECT: 'UPDATE_PROJECT',
  DELETE_PROJECT: 'DELETE_PROJECT',

  // Boards
  CREATE_BOARD: 'CREATE_BOARD',
  UPDATE_BOARD: 'UPDATE_BOARD',
  DELETE_BOARD: 'DELETE_BOARD',

  // Tasks
  CREATE_TASK: 'CREATE_TASK',
  VIEW_TASK: 'VIEW_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  DELETE_TASK: 'DELETE_TASK',
  ASSIGN_TASK: 'ASSIGN_TASK',
  MOVE_TASK: 'MOVE_TASK',
  CHANGE_TASK_PRIORITY: 'CHANGE_TASK_PRIORITY',
  CHANGE_TASK_STATUS: 'CHANGE_TASK_STATUS',

  // Comments
  CREATE_COMMENT: 'CREATE_COMMENT',
  UPDATE_COMMENT: 'UPDATE_COMMENT',
  DELETE_COMMENT: 'DELETE_COMMENT',

  // Chat
  VIEW_CHAT: 'VIEW_CHAT',
  SEND_MESSAGE: 'SEND_MESSAGE',
  DELETE_MESSAGE: 'DELETE_MESSAGE',

  // Settings
  VIEW_SETTINGS: 'VIEW_SETTINGS',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',

  // Analytics
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
};

export const ROLE_PERMISSIONS = {
  [WORKSPACE_MEMBER_ROLE.OWNER]: [
    WORKSPACE_PERMISSION.VIEW_WORKSPACE,
    WORKSPACE_PERMISSION.UPDATE_WORKSPACE,
    WORKSPACE_PERMISSION.DELETE_WORKSPACE,
    WORKSPACE_PERMISSION.ARCHIVE_WORKSPACE,
    WORKSPACE_PERMISSION.VIEW_MEMBERS,
    WORKSPACE_PERMISSION.INVITE_MEMBERS,
    WORKSPACE_PERMISSION.REMOVE_MEMBERS,
    WORKSPACE_PERMISSION.CHANGE_MEMBER_ROLE,
    WORKSPACE_PERMISSION.CREATE_PROJECT,
    WORKSPACE_PERMISSION.VIEW_PROJECT,
    WORKSPACE_PERMISSION.UPDATE_PROJECT,
    WORKSPACE_PERMISSION.DELETE_PROJECT,
    WORKSPACE_PERMISSION.CREATE_BOARD,
    WORKSPACE_PERMISSION.UPDATE_BOARD,
    WORKSPACE_PERMISSION.DELETE_BOARD,
    WORKSPACE_PERMISSION.CREATE_TASK,
    WORKSPACE_PERMISSION.VIEW_TASK,
    WORKSPACE_PERMISSION.UPDATE_TASK,
    WORKSPACE_PERMISSION.DELETE_TASK,
    WORKSPACE_PERMISSION.ASSIGN_TASK,
    WORKSPACE_PERMISSION.MOVE_TASK,
    WORKSPACE_PERMISSION.CHANGE_TASK_PRIORITY,
    WORKSPACE_PERMISSION.CHANGE_TASK_STATUS,
    WORKSPACE_PERMISSION.CREATE_COMMENT,
    WORKSPACE_PERMISSION.UPDATE_COMMENT,
    WORKSPACE_PERMISSION.DELETE_COMMENT,
    WORKSPACE_PERMISSION.VIEW_CHAT,
    WORKSPACE_PERMISSION.SEND_MESSAGE,
    WORKSPACE_PERMISSION.DELETE_MESSAGE,
    WORKSPACE_PERMISSION.VIEW_SETTINGS,
    WORKSPACE_PERMISSION.UPDATE_SETTINGS,
    WORKSPACE_PERMISSION.VIEW_ANALYTICS,
  ],

  [WORKSPACE_MEMBER_ROLE.ADMIN]: [
    WORKSPACE_PERMISSION.VIEW_WORKSPACE,
    WORKSPACE_PERMISSION.UPDATE_WORKSPACE,
    WORKSPACE_PERMISSION.VIEW_MEMBERS,
    WORKSPACE_PERMISSION.INVITE_MEMBERS,
    WORKSPACE_PERMISSION.REMOVE_MEMBERS,
    WORKSPACE_PERMISSION.CHANGE_MEMBER_ROLE,
    WORKSPACE_PERMISSION.CREATE_PROJECT,
    WORKSPACE_PERMISSION.VIEW_PROJECT,
    WORKSPACE_PERMISSION.UPDATE_PROJECT,
    WORKSPACE_PERMISSION.DELETE_PROJECT,
    WORKSPACE_PERMISSION.CREATE_BOARD,
    WORKSPACE_PERMISSION.UPDATE_BOARD,
    WORKSPACE_PERMISSION.DELETE_BOARD,
    WORKSPACE_PERMISSION.CREATE_TASK,
    WORKSPACE_PERMISSION.VIEW_TASK,
    WORKSPACE_PERMISSION.UPDATE_TASK,
    WORKSPACE_PERMISSION.DELETE_TASK,
    WORKSPACE_PERMISSION.ASSIGN_TASK,
    WORKSPACE_PERMISSION.MOVE_TASK,
    WORKSPACE_PERMISSION.CHANGE_TASK_PRIORITY,
    WORKSPACE_PERMISSION.CHANGE_TASK_STATUS,
    WORKSPACE_PERMISSION.CREATE_COMMENT,
    WORKSPACE_PERMISSION.UPDATE_COMMENT,
    WORKSPACE_PERMISSION.DELETE_COMMENT,
    WORKSPACE_PERMISSION.VIEW_CHAT,
    WORKSPACE_PERMISSION.SEND_MESSAGE,
    WORKSPACE_PERMISSION.VIEW_SETTINGS,
    WORKSPACE_PERMISSION.UPDATE_SETTINGS,
    WORKSPACE_PERMISSION.VIEW_ANALYTICS,
  ],

  [WORKSPACE_MEMBER_ROLE.PROJECT_MANAGER]: [
    WORKSPACE_PERMISSION.VIEW_WORKSPACE,
    WORKSPACE_PERMISSION.VIEW_MEMBERS,
    WORKSPACE_PERMISSION.CREATE_PROJECT,
    WORKSPACE_PERMISSION.VIEW_PROJECT,
    WORKSPACE_PERMISSION.UPDATE_PROJECT,
    WORKSPACE_PERMISSION.CREATE_BOARD,
    WORKSPACE_PERMISSION.UPDATE_BOARD,
    WORKSPACE_PERMISSION.CREATE_TASK,
    WORKSPACE_PERMISSION.VIEW_TASK,
    WORKSPACE_PERMISSION.UPDATE_TASK,
    WORKSPACE_PERMISSION.DELETE_TASK,
    WORKSPACE_PERMISSION.ASSIGN_TASK,
    WORKSPACE_PERMISSION.MOVE_TASK,
    WORKSPACE_PERMISSION.CHANGE_TASK_PRIORITY,
    WORKSPACE_PERMISSION.CHANGE_TASK_STATUS,
    WORKSPACE_PERMISSION.CREATE_COMMENT,
    WORKSPACE_PERMISSION.UPDATE_COMMENT,
    WORKSPACE_PERMISSION.DELETE_COMMENT,
    WORKSPACE_PERMISSION.VIEW_CHAT,
    WORKSPACE_PERMISSION.SEND_MESSAGE,
    WORKSPACE_PERMISSION.VIEW_ANALYTICS,
  ],

  [WORKSPACE_MEMBER_ROLE.MEMBER]: [
    WORKSPACE_PERMISSION.VIEW_WORKSPACE,
    WORKSPACE_PERMISSION.VIEW_PROJECT,
    WORKSPACE_PERMISSION.CREATE_TASK,
    WORKSPACE_PERMISSION.VIEW_TASK,
    WORKSPACE_PERMISSION.UPDATE_TASK,
    WORKSPACE_PERMISSION.DELETE_TASK,
    WORKSPACE_PERMISSION.MOVE_TASK,
    WORKSPACE_PERMISSION.CHANGE_TASK_STATUS,
    WORKSPACE_PERMISSION.CREATE_COMMENT,
    WORKSPACE_PERMISSION.UPDATE_COMMENT,
    WORKSPACE_PERMISSION.DELETE_COMMENT,
    WORKSPACE_PERMISSION.VIEW_CHAT,
    WORKSPACE_PERMISSION.SEND_MESSAGE,
  ],
};

export const ROLE_RANK = {
  [WORKSPACE_MEMBER_ROLE.OWNER]: 4,
  [WORKSPACE_MEMBER_ROLE.ADMIN]: 3,
  [WORKSPACE_MEMBER_ROLE.PROJECT_MANAGER]: 2,
  [WORKSPACE_MEMBER_ROLE.MEMBER]: 1,
};

export const hasPermission = (role, permission) =>
  ROLE_PERMISSIONS[role]?.includes(permission) ?? false;

export const hasEveryPermission = (role, permissions) =>
  permissions.every((permission) => hasPermission(role, permission));

export const hasSomePermission = (role, permissions) =>
  permissions.some((permission) => hasPermission(role, permission));

export const getPermissionsForRole = (role) => ROLE_PERMISSIONS[role] ?? [];

export const canManageTargetRole = (actorRole, targetRole) => {
  if (targetRole === WORKSPACE_MEMBER_ROLE.OWNER) {
    return false;
  }

  return ROLE_RANK[actorRole] > ROLE_RANK[targetRole];
};
