export const WORKSPACE_MEMBER_ROLE = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  PROJECT_MANAGER: 'PROJECT_MANAGER',
  MEMBER: 'MEMBER',
};

export const WORKSPACE_MEMBER_MANAGE_ROLES = [
  WORKSPACE_MEMBER_ROLE.OWNER,
  WORKSPACE_MEMBER_ROLE.ADMIN,
];
